### ISSUE TITLE
Compatibility with attiny

### ISSUE THREAD

**Issue by Oitzu** [incmve/generic-rfbox#9]
Quick question:
Are you solely interested to get the generic protocol working on the arduino?
Because i'm trying to create a class that is useable on arduino and attiny boards with examples/sketches targeting different platforms.
At the moment i'm working on getting a sketch ready, running on a attiny85, that reads an tmp36 and sends the data via 433mhz RF, powered by a 3V coin cell.

**Comment by incmve** [comment]
Hi, no I use arduino nano's because they are relatively cheap($3) on ebay and I need 5V for the sonar sensor.
I did use an attiny in the beginning for testing but my RF was not stable enough on 3V.

I have several boxes all with Nano's and every box has a DHT11 and ds18b20 sensor, one box even has a receiver to work as a repeater and send info on request

I am waiting on some wifi transmitters (ESP8266) that is going to replace the 433 RF sender/receiver because the RF reception is poor in my house and I want a 2 way system.

I am thinking about using attiny to build it in a smoke detector for temperature readings and use the piezo buzzer as an interrupt to send a smoke alarm to pimatic, when the attiny goes into deep sleep between readings it should work a long time on the 9V battery.

So little time :)

**Comment by Oitzu** [comment]
I'm mainly interested in the attiny because of the low power consumption in sleep mode.
And therefore a long livetime on batterys.
The reception on a 3V coin cell is not very good but should be good enough to get signals from across the room or next room from the receiver.
Anything further needs some sort of relay.

The wifi transmitter looks interesting. Could maybe even used to build some sort of 433mhz to wifi bridge. This would eliminate the need to replace every 433mhz transmitter.

Are you interested to merge the class structure https://github.com/Oitzu/pimatic-probe (PimaticProbe.cpp/PimaticProbe.h)? I think its nicer to use a class instead of copy/pasting the send code to every sketch.

**Comment by incmve** [comment]
I agree, working with a class is much cleaner. looks nice I never took the time to build it.
I am going to merge it, thanks!
